maxLevel: 100
levels:
  # 1:
  # quests:
  # 1:   # 破坏所有种类的木头
  # type: BREAK
  # name: "破坏12个任意种类的木头"
  # variable: ANY_LOG
  # needProgress: 12
  # 2:    # 破坏一种方块
  # type: BREAK
  # name: "破坏12个石头"
  # variable: STONE
  # needProgress: 12
  # 3:
  # type: KILL_MOB
  # name: "击杀10个僵尸"
  # variable: ZOMBIE
  # needProgress: 10
  # #      - "PLACE;STONE;12"      # 放置一种方块
  # #      - "CRAFT;WORKBENCH;1"      # 合成物品
  # #      - "CONSUME;BEEF;1"      # 吃东西
  # #      - "KILL_MOB;ZOMBIE;10"
  # #      - "DAMAGE_MOB;ZOMBIE;10000"
  # #      - "DAMAGE_PLAYER;10000"
  # #      - "KILL_PLAYER;10"
  # #      - "ENCHANT;10"
  # #      - "SMELT;COAL;10"
  # #      - "HONEY_EXTRACT;10"
  # commonRewards:
  # 1:
  # desc: "&ex1,000 经验值"
  # type: EXP
  # amount: 1000
  # 2:
  # desc: "&fx1 初学者铁镐"
  # type: ITEM
  # amount: 1
  # variable: IRON_PICKAXE
  # premiumRewards:
  # 1:
  # desc: "&ex1,000 经验值"
  # type: EXP
  # amount: 1000
  # 2:
  # desc: "&fx1 初学者铁镐"
  # type: ITEM
  # amount: 1
  # variable: IRON_PICKAXE
  # #      - "EXP;1000"
  # #      - "MONEY;1000"
  # #      - "RUBY;1000"
  # #      - "ITEM;WOODEN_PICKAXE;1"
  # #      - "CUSTOM_ITEM;pwpickaxe;1"
  1:
    quests:
      1:
        type: BREAK
        name: "破坏15个任意种类的方块"
        variable: ANY_BLOCK
        needProgress: 15
    commonRewards:
      1:
        desc: "&ax32 橡木"
        type: ITEM
        variable: OAK_WOOD
        amount: 32
      2:
        desc: "&6x16 牛排"
        type: ITEM
        variable: COOKED_BEEF
        amount: 16
      3:
        desc: "&7x1 初学者石镐 &7(耐久 I)"
        type: CUSTOM_ITEM
        amount: 1
        variable: starter_stone_pickaxe
      4:
        desc: "&7解锁等级样式 &7<&f1&7>"
        type: NONE
        amount: 1
    premiumRewards:
      1:
        desc: "&fx1 初学者铁镐 &7(耐久 I)"
        type: CUSTOM_ITEM
        amount: 1
        variable: starter_iron_pickaxe
      2:
        desc: "&7解锁等级样式 &7<&f1+&7>"
        type: NONE
        amount: 1
  2:
    quests:
      1:
        type: BREAK
        name: "破坏16个煤矿"
        variable: "COAL_ORE;DEEPSLATE_COAL_ORE"
        needProgress: 16
      2:
        type: BREAK
        name: "破坏8个铁矿"
        variable: "IRON_ORE;DEEPSLATE_IRON_ORE"
        needProgress: 8
      3:
        type: CRAFT
        name: "制作1把石镐"
        variable: STONE_PICKAXE
        needProgress: 1
      4:
        type: CRAFT
        name: "制作1把石剑"
        variable: STONE_SWORD
        needProgress: 1
      5:
        type: CRAFT
        name: "制作1把石斧"
        variable: STONE_AXE
        needProgress: 1
      6:
        type: CRAFT
        name: "制作1把石铲"
        variable: STONE_SHOVEL
        needProgress: 1
      7:
        type: CRAFT
        name: "制作1把石锄"
        variable: STONE_HOE
        needProgress: 1
    commonRewards:
      1:
        desc: "&fx128 石头"
        type: ITEM
        variable: STONE
        amount: 128
      2:
        desc: "&7x1 初学者石斧 &7(耐久 I)"
        type: CUSTOM_ITEM
        amount: 1
        variable: starter_stone_axe
    premiumRewards:
      1:
        desc: "&fx1 初学者铁斧 &7(耐久 I)"
        type: CUSTOM_ITEM
        amount: 1
        variable: starter_iron_axe
  3:
    quests:
      1:
        type: BREAK
        name: "破坏32个橡木"
        variable: "OAK_WOOD;OAK_LOG"
        needProgress: 32
      2:
        type: BREAK
        name: "破坏32个从林木"
        variable: "JUNGLE_WOOD;JUNGLE_LOG"
        needProgress: 32
    commonRewards:
      1:
        desc: "&6x32 铁锭"
        type: ITEM
        variable: IRON_INGOT
        amount: 32
      2:
        desc: "&7x1 初学者石剑 &7(耐久 I)"
        type: CUSTOM_ITEM
        amount: 1
        variable: starter_stone_sword
    premiumRewards:
      1:
        desc: "&bx5 钻石"
        type: ITEM
        variable: DIAMOND
        amount: 5
      2:
        desc: "&fx1 初学者铁剑 &7(耐久 I)"
        type: CUSTOM_ITEM
        amount: 1
        variable: starter_iron_sword
  4:
    quests:
      1:
        type: KILL_MOB
        name: "击杀15个僵尸"
        variable: "ZOMBIE"
        needProgress: 15
      2:
        type: KILL_MOB
        name: "击杀15个普通蜘蛛"
        variable: "SPIDER"
        needProgress: 15
      3:
        type: KILL_MOB
        name: "击杀15个骷髅"
        variable: "SKELETON"
        needProgress: 15
      4:
        type: KILL_MOB
        name: "击杀15个爬行者"
        variable: "CREEPER"
        needProgress: 15
    commonRewards:
      1:
        desc: "&5x20 紫宝石"
        type: RUBY
        amount: 20
      2:
        desc: "&Fx1 初学者铁头盔 &7(耐久 II)"
        type: CUSTOM_ITEM
        amount: 1
        variable: starter_iron_helmet
      3:
        desc: "&Fx1 初学者铁胸甲 &7(耐久 II)"
        type: CUSTOM_ITEM
        amount: 1
        variable: starter_iron_chestplate
      4:
        desc: "&Fx1 初学者铁护腿 &7(耐久 II)"
        type: CUSTOM_ITEM
        amount: 1
        variable: starter_iron_leggings
      5:
        desc: "&Fx1 初学者铁靴子 &7(耐久 II)"
        type: CUSTOM_ITEM
        amount: 1
        variable: starter_iron_boots
    premiumRewards:
      1:
        desc: "&5x40 紫宝石"
        type: RUBY
        amount: 40
      2:
        desc: "&bx1 初学者钻石头盔 &7(耐久 II 保护 I)"
        type: CUSTOM_ITEM
        amount: 1
        variable: starter_diamond_helmet
      3:
        desc: "&bx1 初学者钻石胸甲 &7(耐久 II 保护 I)"
        type: CUSTOM_ITEM
        amount: 1
        variable: starter_diamond_chestplate
      4:
        desc: "&bx1 初学者钻石护腿 &7(耐久 II 保护 I)"
        type: CUSTOM_ITEM
        amount: 1
        variable: starter_diamond_leggings
      5:
        desc: "&bx1 初学者钻石靴子 &7(耐久 II 保护 I)"
        type: CUSTOM_ITEM
        amount: 1
        variable: starter_diamond_boots
  5:
    quests:
      1:
        type: KILL_PLAYER
        name: "击杀5个玩家"
        needProgress: 5
        variable: kill_player
    commonRewards:
      1:
        desc: "&5x30 紫宝石"
        type: RUBY
        amount: 30
      2:
        desc: "&ax1000 EXP"
        type: EXP
        amount: 1000
      3:
        desc: "&ex500 金钱"
        type: MONEY
        amount: 500
    premiumRewards:
      1:
        desc: "&5x60 紫宝石"
        type: RUBY
        amount: 60
      2:
        desc: "&ax2000 EXP"
        type: EXP
        amount: 2000
      3:
        desc: "&ex1000 金钱"
        type: MONEY
        amount: 1000
  6:
    quests:
      1:
        type: KILL_HUNTED_PLAYER
        name: "击杀1个被悬赏的玩家"
        needProgress: 1
        variable: kill_hunted_player
    commonRewards:
      1:
        desc: "&5x50 紫宝石"
        type: RUBY
        amount: 50
      2:
        desc: "&ex800 金钱"
        type: MONEY
        amount: 500
    premiumRewards:
      1:
        desc: "&5x150 紫宝石"
        type: RUBY
        amount: 150
      2:
        desc: "&ex1400 金钱"
        type: MONEY
        amount: 1000

